export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LIST_TODOS_REQUEST = 'USER_LIST_TODOS_REQUEST';
export const USER_LIST_TODOS_SUCCESS = 'USER_LIST_TODOS_SUCCESS';
export const USER_LIST_TODOS_FAIL = 'USER_LIST_TODOS_FAIL';
export const USER_LIST_TODOS_EMPTY = 'USER_LIST_TODOS_EMPTY';

export const USER_ADD_TODO_REQUEST = 'USER_ADD_TODO_REQUEST';
export const USER_ADD_TODO_SUCCESS = 'USER_ADD_TODO_SUCCESS';
export const USER_ADD_TODO_FAIL = 'USER_ADD_TODO_FAIL';

export const USER_REMOVE_TODO_REQUEST = 'USER_REMOVE_TODO_REQUEST';
export const USER_REMOVE_TODO_SUCCESS = 'USER_REMOVE_TODO_SUCCESS';
export const USER_REMOVE_TODO_FAIL = 'USER_REMOVE_TODO_FAIL';
